## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer
accel_y_min: -277.00
accel_y_max: 266.0
accel_x_min: -263.0
accel_x_max: 286.0
accel_z_min: -297.0
accel_z_max: 296.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [189.538, -48.9203, 38.084]
magn_ellipsoid_transform: [[0.824872, 0.0224794, -0.0154017], [0.0224794, 0.858387, 0.0176368], [-0.0154017, 0.0176368, 0.996878]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_y: -62.11
gyro_average_offset_x: 4.21
gyro_average_offset_z: -4.61
